[project]
name = "truco"
version = "0.1.0"
description = "Sistema Multiagentes de Truco Mineiro com agentes BDI e FIPA-ACL"
readme = "README.md"
authors = [
    { name = "rafaelghiorzi", email = "rafael.ghiorzi@gmail.com" },
    { name = "Lucas Saad Rodrigues", email = ""},
    { name = "Lucca Schoen de Almeida", email = ""}
]
requires-python = ">=3.14"
dependencies = [
    "greenlet>=3.5.6",
    "spade>=4.1.4",
]

[project.scripts]
truco = "truco.main:run"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
